#!/bin/bash
clear
cd
sudo mv UTOL utol || clear

sudo mv utol/UTOL /bin/UTOL
sudo mv utol/UUUTTTOOO3 /bin/uchange
sudo chmod +x /bin/UTOL
sudo chmod +x /bin/uchange
sudo chmod +x utol/install

sudo chmod +x utol/README.md

rm utol/install

rm utol/README.md
