#!/bin/bash
cd
echo UTOL/
read input
if [ "$input" == "update" ]; then
echo Update UTOL? All Files In util Folder Will Be Lost, and the new update may be fatal. [y,n]
read input
if [ "$input" == "y" ]; then
cd
sudo rm -rf utol
git clone https://github.com/ABadCoder1234/utol
sudo chmod +x ./utol/install 
./utol/install
S=1
else
echo Cancelled update
fi
else
if [ "$input" == "help" ]; then
echo Command list
echo update -Updates utol
echo about -Tells info about utol
echo down -Opens download utility
echo gdown -Opens github download utility
echo ctrl+c to cancel utol at any time
sleep 0.9
UTOL
S=1
else
if [ "$input" == "about" ]; then
echo UTOL --Utility Tool On Linux-- V.0.3.1
echo DU --Download Utility-- kjklk v.1.01
echo GDU -- Git Download Utility-- kjklk-hit v1.0
echo Run help for commands
S=1
fi
if [ "$input" == "down" ]; then
echo Starting kjklk v1.01
sleep 3
echo Enter URL
read input
if [ "$input" == "cancel" ]; then
echo Cancelled
else
cd
cd utol
wget -O SIP $input
echo Save as --No spaces--
read input
mv utol/SIP utol/$input
echo Saved file as $input
S=1
fi
else
if [ "$input" == "gdown" ]; then
echo Opening kjklk-git v1.0
cd
cd utol
echo Repository URL --username/repo--
read input
if [ "$input" == "cancel" ]; then
echo Cancelled
else
git clone https://github.com/$input
cd
echo Saved repository
S=1
fi
fi
fi
fi
fi
fi
if [ "$S" == "1" ]; then
sleep 0.6
else
echo There was a small error somewhere, try updating.
fi
