#!/bin/bash
cd
clear
echo UTOL/
read input
if [ "$input" == "modbreak" ]; then
sudo nano /bin/UTOL
S=1
fi
if [ "$input" == "update" ]; then
echo Update? [y,n]
read input
if [ "$input" == "y" ]; then
cd
mv utol UTOL
git clone https://github.com/ABadCoder1234/utol
sudo chmod +x ./utol/install 
./utol/install
mv UTOL utol
S=1
else
echo Cancelled update
fi
fi
if [ "$input" == "help" ]; then
clear
echo Using UTOL
echo Upon typing $ UTOL into shell, you are greeted with UTOL/ this is where you type the command
echo it is like UTOL/-----, when commands are listed it will say UTOL/[COMMAND].
echo Only copy the part after UTOL/ for your command.
echo
echo
echo Using Menu
echo The menu is a nice way to see utol. To use the menu, use UTOL/menu.
echo When you open the menu you see a bunch a commands, press the highlighted letter and enter
echo For exaple, for help as you can see *h* is highlighted, like *h*elp
echo
echo
echo Available commands
echo UTOL/update -Updates utol
echo UTOL/about -Tells info about utol
echo down -Opens download utility
echo gdown -Opens github download utility
echo ctrl+c to cancel utol at any time
sleep 0.9
clear
UTOL
S=1fi
if [ "$input" == "about" ]; then
echo UTOL --Utility Tool On Linux-- V.0.3.1
echo DU --Download Utility-- kjklk v.1.01
echo GDU -- Git Download Utility-- kjklk-hit v1.0
echo Run help for commands
S=1
fi
if [ "$input" == "down" ]; then
echo Starting kjklk v1.01
sleep 3
echo Enter URL
read input
if [ "$input" == "cancel" ]; then
echo Cancelled
else
cd
cd utol
wget -O SIP $input
echo Save as --No spaces--
read input
mv utol/SIP utol/$input
echo Saved file as $input
S=1
fi
fi
if [ "$input" == "gdown" ]; then
echo Opening kjklk-git v1.0
cd
cd utol
echo Repository URL --username/repo--
read input
if [ "$input" == "cancel" ]; then
echo Cancelled
else
cd
git clone https://github.com/$input
echo Saved repository
S=1
fi
fi
fi
if [ "$input" == "menu" ]; then
echo *a*bout
echo *c*hangelog
echo *d*ownload package
echo *h*elp
echo *i*nverse colors
echo *u*pdate 
read -rsn1 input
if [ "$input" == "a" ]; then
echo UTOL --Utility Tool On Linux-- V.0.3.1
echo DU --Download Utility-- kjklk v.1.01
echo GDU -- Git Download Utility-- kjklk-hit v1.0
echo UTOL/help for command list
S=1
fi
if [ "$input" == "d" ]; then
echo Get what package?
read input
sudo apt-get install -y $input
fi
if [ "$input" == "h" ]; then
clear
echo Using UTOL
echo Upon typing $ UTOL into shell, you are greeted with UTOL/ this is where you type the command
echo it is like UTOL/-----, when commands are listed it will say UTOL/[COMMAND].
echo Only copy the part after UTOL/ for your command.
echo
echo
echo Using Menu
echo The menu is a nice way to see utol. To use the menu, use UTOL/menu.
echo When you open the menu you see a bunch a commands, press the highlighted letter and enter
echo For exaple, for help as you can see *h* is highlighted, like *h*elp
echo
echo
echo Available commands
echo UTOL/update -Updates utol
echo UTOL/about -Tells info about utol
echo down -Opens download utility
echo gdown -Opens github download utility
echo ctrl+c to cancel utol at any time
sleep 0.9
clear
UTOL
S=1
fi
if [ "$input" == "u" ]; then
echo Update? [y,n]
read input
if [ "$input" == "y" ]; then
cd
mv utol UTOL
git clone https://github.com/ABadCoder1234/utol
sudo chmod +x ./utol/install 
./utol/install
mv UTOL utol
S=1
else
S=1
fi
fi
if [ "$input" == "c" ]; then
clear
echo Version pre-1.o changelog 
echo Cleaned up commands a lot, use *help* to see new commands
echo Added menu with changelog and inverse colors
echo 
echo
echo
echo
echo Press any key to continue
read -rsn1 input
S=1
else
if [ "$input" == "i" ]; then
echo 1. Turn it on
echo 2. Turn it off
read -rsn1 input
S=1
if [ "$input" == "1" ]; then
setterm --inversescreen on
echo Setting turned on
sleep 3
else
setterm --inversescreen off
echo Setting turned off
S=1
fi
fi
fi
fi
if [ "$S" == "1" ]; then
sleep 0.6
else
echo Invalid/broken command or operator. If everything went fine ignore this message
fi
